permalink:   none
lsi:         false
kramdown:
  auto_ids:  false
  syntax_highlighter_opts:
    disable: true
exclude:
  - Gemfile
  - Gemfile.lock
  - script
  - README.markdown

title: "Why's (Poignant) Guide to Ruby"
